INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('blush', 'https://i.imgur.com/I8pZJth.gif', '**blushes**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('blush', 'https://i.imgur.com/xwVyOZW.gif', '**blushes**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('blush', 'https://i.imgur.com/rfk1CyH.gif', '**blushes**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('blush', 'https://i.imgur.com/KQCG6xt.gif', '**blushes**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('blush', 'https://i.imgur.com/zLxohfr.gif', '**blushes**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('blush', 'https://i.imgur.com/CkcsUpo.gif', '**blushes**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('cuddle', 'https://i.imgur.com/pon1SjU.gif', '**${mentioned}, you have been cuddled by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('cuddle', 'https://i.imgur.com/z5b6UZn.gif', '**${mentioned}, you have been cuddled by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('cuddle', 'https://i.imgur.com/A6yUsVe.gif', '**${mentioned}, you have been cuddled by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('cuddle', 'https://i.imgur.com/HvA8ZxM.gif', '**${mentioned}, you have been cuddled by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('cuddle', 'https://i.imgur.com/jnSZxet.gif', '**${mentioned}, you have been cuddled by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('cuddle', 'https://i.imgur.com/P2ADvTX.gif', '**${mentioned}, you have been cuddled by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('cuddle', 'https://i.imgur.com/Mlf88U8.gif', '**${mentioned}, you have been cuddled by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('cuddle', 'https://i.imgur.com/aT6jR8g.gif', '**${mentioned}, you have been cuddled by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('hug', 'https://i.imgur.com/GykCWJG.gif', '**${mentioned}, you have been hugged by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('hug', 'https://i.imgur.com/M29Yxd3.gif', '**${mentioned}, you have been hugged by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('hug', 'https://i.imgur.com/OyF4XgG.gif', '**${mentioned}, you have been hugged by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('hug', 'https://i.imgur.com/jaSYl0V.gif', '**${mentioned}, you have been hugged by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('hug', 'https://i.imgur.com/kuexllr.gif', '**${mentioned}, you have been hugged by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('kiss', 'https://i.imgur.com/9zfV5FC.gif', '**${mentioned}, you have been kissed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('kiss', 'https://i.imgur.com/sACkmhz.gif', '**${mentioned}, you have been kissed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('kiss', 'https://i.imgur.com/0o07n8S.gif', '**${mentioned}, you have been kissed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('kiss', 'https://i.imgur.com/iNKqm3X.gif', '**${mentioned}, you have been kissed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('kiss', 'https://i.imgur.com/BT1N80N.gif', '**${mentioned}, you have been kissed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('kiss', 'https://i.imgur.com/p4VCGng.gif', '**${mentioned}, you have been kissed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('nom', 'https://i.imgur.com/PyBEovX.gif', '**${mentioned}, you have been nommed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('nom', 'https://i.imgur.com/FsqAVY5.gif', '**${mentioned}, you have been nommed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('nom', 'https://i.imgur.com/68ufjPM.gif', '**${mentioned}, you have been nommed by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pat', 'https://i.imgur.com/ZgbLAf2.gif', '**${mentioned}, you have been pat by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pat', 'https://i.imgur.com/qFEM1ir.gif', '**${mentioned}, you have been pat by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pat', 'https://i.imgur.com/LSEhAnO.gif', '**${mentioned}, you have been pat by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pat', 'https://i.imgur.com/kzTjXPM.gif', '**${mentioned}, you have been pat by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pat', 'https://i.imgur.com/6ZgEvBN.gif', '**${mentioned}, you have been pat by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pat', 'https://i.imgur.com/Gu7hvna.gif', '**${mentioned}, you have been pat by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pat', 'https://i.imgur.com/KJHTFtE.gif', '**${mentioned}, you have been pat by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pat', 'https://i.imgur.com/GUKQtWv.gif', '**${mentioned}, you have been pat by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/BzFQWJr.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/GSdJlOO.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/Zn5p5Ng.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/cvI9qqk.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/dy5fPyP.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/DjiD21h.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/hm3qrvP.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/nbgYZcp.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/2uLoIzt.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/T6Ovbbv.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/6Ba7PFu.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/1gs4Tsw.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('pout', 'https://i.imgur.com/IUtq6kM.gif', '**${mentioned}, you have been pouted at by ${author}.**');
INSERT INTO response_command_entries (command_name, embed_image, embed_description) VALUES ('slap', 'https://i.imgur.com/B4CRs04.gif', '**${mentioned}, you have been slapped by ${author}.**');